# Generated by Django 5.2.15 on 2026-07-06 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0009_alter_flightworkflowstep_step'),
        ('staff', '0006_alter_staff_staff_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnaroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('CHOCKS_ON', 'Chocks On'), ('DEBOARDING', 'Passenger Deboarding'), ('FUELING', 'Fueling'), ('CATERING', 'Catering'), ('CABIN_CLEANING', 'Cabin Cleaning'), ('WATER_SERVICE', 'Water Service'), ('LAVATORY_SERVICE', 'Lavatory Service'), ('BAGGAGE_UNLOADING', 'Baggage Unloading'), ('BAGGAGE_LOADING', 'Baggage Loading'), ('CARGO_LOADING', 'Cargo Loading'), ('PUSHBACK_READY', 'Pushback Ready'), ('BOARDING_COMPLETE', 'Boarding Complete'), ('DOORS_CLOSED', 'Doors Closed'), ('PUSHBACK', 'Pushback'), ('TAKEOFF_READY', 'Takeoff Ready')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnaround_tasks', to='staff.staff')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_turnaround_tasks', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnaround_tasks', to='flights.flight')),
            ],
            options={
                'ordering': ['flight', 'scheduled_time'],
                'indexes': [models.Index(fields=['status'], name='turnaround__status_701762_idx'), models.Index(fields=['task_type'], name='turnaround__task_ty_87bb9f_idx')],
                'unique_together': {('flight', 'task_type')},
            },
        ),
    ]
