# Generated by Django 5.2.15 on 2026-07-06 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_equipment', '0001_initial'),
        ('turnaround', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnaroundtask',
            name='assigned_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnaround_tasks', to='ground_equipment.groundequipment'),
        ),
        migrations.AddField(
            model_name='turnaroundtask',
            name='delay_reason',
            field=models.CharField(blank=True, choices=[('NONE', 'No Delay'), ('FUEL', 'Fuel'), ('WEATHER', 'Weather'), ('CLEANING', 'Cleaning'), ('CREW', 'Crew'), ('GATE_UNAVAILABLE', 'Gate Unavailable'), ('EQUIPMENT_UNAVAILABLE', 'Equipment Unavailable'), ('BAGGAGE', 'Baggage Handling'), ('CATERING', 'Catering'), ('OTHER', 'Other')], default='NONE', max_length=30),
        ),
    ]
