# Generated by Django 5.2.15 on 2026-06-30 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0005_flightservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('DELAY', 'Delay Prediction'), ('MAINTENANCE', 'Predictive Maintenance'), ('GATE', 'Gate Recommendation'), ('STAFF', 'Staff Requirement'), ('PASSENGER_RUSH', 'Passenger Rush'), ('WEATHER_RISK', 'Weather Risk'), ('RESOURCE', 'Resource Optimization')], max_length=30)),
                ('input_data', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='flights.flight')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prediction_type'], name='ai_module_a_predict_5f9b35_idx'), models.Index(fields=['status'], name='ai_module_a_status_85c3fc_idx')],
            },
        ),
    ]
