# Generated by Django 5.2.15 on 2026-07-02 08:23

import ai_module.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightScheduleUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=ai_module.models.schedule_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='PROCESSED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightScheduleRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(blank=True, max_length=30)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ai_module.flightscheduleupload')),
            ],
            options={
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['scheduled_time'], name='ai_module_f_schedul_79b300_idx')],
            },
        ),
    ]
