# Generated by Django 5.2.15 on 2026-07-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0009_alter_flightworkflowstep_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_gate', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('BOARDING', 'Boarding'), ('FINAL_CALL', 'Final Call'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20)),
                ('boarding_started_at', models.DateTimeField(blank=True, null=True)),
                ('boarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('final_call_at', models.DateTimeField(blank=True, null=True)),
                ('passenger_count', models.PositiveIntegerField(blank=True, null=True)),
                ('passengers_boarded', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_session', to='flights.flight')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('passenger_count', models.PositiveIntegerField(default=0)),
                ('boarding_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='passenger_boarding.boardingsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='boardingsession',
            index=models.Index(fields=['status'], name='passenger_b_status_26c5d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boardinggroup',
            unique_together={('boarding_session', 'group_name')},
        ),
    ]
