# Generated by Django 5.2.15 on 2026-07-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0009_alter_flightworkflowstep_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_number', models.CharField(max_length=50, unique=True)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_manifest', to='flights.flight')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ULD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uld_id', models.CharField(help_text='Container or pallet identifier, e.g. AKE12345', max_length=20, unique=True)),
                ('uld_type', models.CharField(choices=[('CONTAINER', 'Container'), ('PALLET', 'Pallet')], max_length=20)),
                ('status', models.CharField(choices=[('EMPTY', 'Empty'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('IN_TRANSIT', 'In Transit'), ('OFFLOADED', 'Offloaded'), ('DAMAGED', 'Damaged')], default='EMPTY', max_length=20)),
                ('position', models.CharField(blank=True, default='', help_text='Aircraft hold position, e.g. AKE-1', max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ulds', to='flights.flight')),
            ],
            options={
                'ordering': ['uld_id'],
            },
        ),
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_number', models.CharField(blank=True, default='', help_text='Air Waybill number', max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WAREHOUSE', 'In Warehouse'), ('LOADED', 'Loaded'), ('OFFLOADED', 'Offloaded'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('is_dangerous_goods', models.BooleanField(default=False)),
                ('dangerous_goods_class', models.CharField(blank=True, choices=[('', 'Not Dangerous Goods'), ('CLASS_1', 'Class 1 - Explosives'), ('CLASS_2', 'Class 2 - Gases'), ('CLASS_3', 'Class 3 - Flammable Liquids'), ('CLASS_4', 'Class 4 - Flammable Solids'), ('CLASS_5', 'Class 5 - Oxidizers'), ('CLASS_6', 'Class 6 - Toxic Substances'), ('CLASS_7', 'Class 7 - Radioactive'), ('CLASS_8', 'Class 8 - Corrosives'), ('CLASS_9', 'Class 9 - Miscellaneous')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cargo_management.cargomanifest')),
                ('uld', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_items', to='cargo_management.uld')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uld',
            index=models.Index(fields=['status'], name='cargo_manag_status_3db965_idx'),
        ),
        migrations.AddIndex(
            model_name='cargoitem',
            index=models.Index(fields=['status'], name='cargo_manag_status_2f7588_idx'),
        ),
        migrations.AddIndex(
            model_name='cargoitem',
            index=models.Index(fields=['is_dangerous_goods'], name='cargo_manag_is_dang_39a292_idx'),
        ),
    ]
