# Generated by Django 5.2.15 on 2026-06-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('gates', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gateassignment',
            unique_together={('flight', 'gate')},
        ),
    ]
