# Generated by Django 5.2.15 on 2026-07-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0002_alter_gateassignment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='gate_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=20),
        ),
        migrations.AddField(
            model_name='gate',
            name='is_under_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gate',
            name='length',
            field=models.DecimalField(decimal_places=2, default=45.0, help_text='Usable length in meters, used for aircraft compatibility checks', max_digits=6),
        ),
        migrations.AddField(
            model_name='gate',
            name='width',
            field=models.DecimalField(decimal_places=2, default=45.0, help_text='Usable width in meters, used for aircraft compatibility checks', max_digits=6),
        ),
        migrations.AddField(
            model_name='gateassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('released', 'Released')], default='assigned', max_length=20),
        ),
    ]
