# Generated by Django 5.2.15 on 2026-07-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0003_gate_gate_type_gate_is_under_maintenance_gate_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gate',
            options={'ordering': ['gate_number']},
        ),
    ]
