# Generated by Django 5.2.15 on 2026-07-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0004_alter_gate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='body_type',
            field=models.CharField(choices=[('narrow_body', 'Narrow-Body'), ('wide_body', 'Wide-Body')], default='narrow_body', help_text='Aircraft size class the gate is designed for.', max_length=20),
        ),
        migrations.AddField(
            model_name='gate',
            name='connection_type',
            field=models.CharField(choices=[('contact', 'Contact (Jet Bridge)'), ('remote', 'Remote (Apron Stand)')], default='contact', help_text='Contact (jet bridge) or remote (apron stand, bus transfer).', max_length=20),
        ),
        migrations.AddField(
            model_name='gate',
            name='purpose',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('cargo', 'Cargo')], default='passenger', help_text='Passenger gate or dedicated cargo stand.', max_length=20),
        ),
        migrations.AlterField(
            model_name='gate',
            name='gate_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International'), ('swing', 'Swing')], default='domestic', help_text='Traffic type: domestic, international, or swing (either).', max_length=20),
        ),
    ]
