# Generated by Django 5.2.15 on 2026-06-29 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_type'], name='staff_staff_staff_t_229c99_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active'], name='staff_staff_is_acti_0db61a_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['employee_id'], name='staff_staff_employe_f8cd0b_idx'),
        ),
    ]
