# Generated by Django 5.2.15 on 2026-06-30 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flightservice'),
        ('staff', '0004_staff_staff_staff_staff_t_229c99_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='flights.flight')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='staff.staff')),
            ],
            options={
                'unique_together': {('staff', 'flight')},
            },
        ),
    ]
