# Generated by Django 5.2.15 on 2026-06-25 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baggage_tag', models.CharField(max_length=50, unique=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='BaggageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('LOADED', 'Loaded'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('CLAIMED', 'Claimed')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baggage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baggage.baggage')),
            ],
        ),
    ]
