# Generated by Django 5.2.15 on 2026-06-27 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baggagetracking',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='baggagetracking',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='baggagetracking',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='baggagetracking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='baggagetracking',
            name='baggage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='baggage.baggage'),
        ),
        migrations.AlterField(
            model_name='baggagetracking',
            name='status',
            field=models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('LOADED', 'Loaded'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('CLAIMED', 'Claimed'), ('MISSING', 'Missing')], max_length=20),
        ),
    ]
