# Generated by Django 5.2.15 on 2026-07-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0002_alter_baggagetracking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baggage',
            options={'ordering': ['baggage_tag']},
        ),
    ]
