# Generated by Django 5.2.15 on 2026-07-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baggage', '0003_alter_baggage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='baggage',
            name='baggage_type',
            field=models.CharField(choices=[('CARRY_ON', 'Carry-on (Cabin)'), ('CHECKED', 'Checked'), ('PERSONAL_ITEM', 'Personal Item'), ('SPECIAL', 'Special')], default='CHECKED', help_text='Carry-on: taken into the cabin by the passenger, subject to airline size/weight limits. Checked: handed over at check-in and transported in the cargo hold. Personal item: a small bag (handbag, laptop bag, small backpack) that fits under the seat in front. Special: items needing special handling (sports equipment, musical instruments, wheelchairs, strollers, fragile items), may involve extra fees or packing.', max_length=20),
        ),
        migrations.AddField(
            model_name='baggage',
            name='is_special_handling',
            field=models.BooleanField(default=False, help_text='Set for special baggage requiring extra fees/packing (e.g. sports gear, instruments, wheelchairs, strollers, fragile items).'),
        ),
        migrations.AddField(
            model_name='baggage',
            name='special_handling_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
