# Generated by Django 5.2.15 on 2026-06-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('GROUND_STAFF', 'Ground Staff'), ('MAINTENANCE_ENGINEER', 'Maintenance Engineer'), ('GATE_MANAGER', 'Gate Manager'), ('HR', 'HR'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('BAGGAGE_SUPERVISOR', 'Baggage Supervisor'), ('SECURITY_OFFICER', 'Security Officer'), ('VIEWER', 'Viewer'), ('SUPERVISOR', 'Supervisor (legacy)'), ('MAINTENANCE', 'Maintenance (legacy)')], default='VIEWER', max_length=30),
        ),
    ]
