# Generated by Django 5.2.15 on 2026-07-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('GROUND_STAFF', 'Ground Staff'), ('MAINTENANCE_ENGINEER', 'Maintenance Engineer'), ('GATE_MANAGER', 'Gate Manager'), ('HR', 'HR'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('BAGGAGE_SUPERVISOR', 'Baggage Supervisor'), ('SECURITY_OFFICER', 'Security Officer'), ('VIEWER', 'Viewer'), ('RAMP_SUPERVISOR', 'Ramp Supervisor'), ('RAMP_AGENT', 'Ramp Agent'), ('APRON_CONTROLLER', 'Apron Controller'), ('DISPATCHER', 'Dispatcher'), ('LOAD_CONTROLLER', 'Load Controller'), ('FLIGHT_COORDINATOR', 'Flight Coordinator'), ('OCC_MANAGER', 'Operations Control Center Manager'), ('FUEL_SUPERVISOR', 'Fuel Supervisor'), ('CATERING_SUPERVISOR', 'Catering Supervisor'), ('CLEANING_SUPERVISOR', 'Cleaning Supervisor'), ('CARGO_SUPERVISOR', 'Cargo Supervisor'), ('IMMIGRATION_OFFICER', 'Immigration Officer'), ('CUSTOMS_OFFICER', 'Customs Officer'), ('AIRSIDE_DRIVER', 'Airside Driver'), ('SUPERVISOR', 'Supervisor (legacy)'), ('MAINTENANCE', 'Maintenance (legacy)')], default='VIEWER', max_length=30),
        ),
    ]
