# Generated by Django 5.2.15 on 2026-07-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0009_alter_flightworkflowstep_step'),
        ('staff', '0006_alter_staff_staff_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLavatoryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potable_water_refilled', models.BooleanField(default=False)),
                ('water_quantity_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lavatory_serviced', models.BooleanField(default=False)),
                ('waste_disposed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_lavatory_services', to='staff.staff')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_lavatory_services', to='flights.flight')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='water_lavat_status_ec986a_idx')],
            },
        ),
    ]
