# Generated by Django 5.2.15 on 2026-07-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0009_alter_flightworkflowstep_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Catering companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CateringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('STANDARD', 'Standard'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('DIABETIC', 'Diabetic'), ('KOSHER', 'Kosher'), ('HALAL', 'Halal'), ('GLUTEN_FREE', 'Gluten Free'), ('CHILD', 'Child Meal'), ('INFANT', 'Infant Meal')], default='STANDARD', max_length=20)),
                ('meal_count', models.PositiveIntegerField(default=0)),
                ('is_special_meal', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('IN_TRANSIT', 'In Transit'), ('LOADED', 'Loaded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('loading_completed', models.BooleanField(default=False)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catering_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catering.cateringcompany')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_orders', to='flights.flight')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='catering_ca_status_0edaf2_idx'), models.Index(fields=['meal_type'], name='catering_ca_meal_ty_b518bb_idx')],
            },
        ),
    ]
