# Generated by Django 5.2.15 on 2026-06-30 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_flights_fli_status_e6e528_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('GATE_ASSIGNED', 'Gate Assigned'), ('CREW_ASSIGNED', 'Ground Crew Assigned'), ('FUELING', 'Fuel Assigned'), ('CLEANING', 'Cleaning Started'), ('MAINTENANCE_CHECK', 'Maintenance Check'), ('BAGGAGE_LOADING', 'Baggage Loading'), ('BOARDING', 'Boarding'), ('GATE_CLOSED', 'Gate Closed'), ('PUSHBACK', 'Pushback'), ('TAXIING', 'Taxiing'), ('DEPARTED', 'Departed'), ('AIRBORNE', 'Airborne'), ('LANDING', 'Landing'), ('TAXI_TO_GATE', 'Taxi to Gate'), ('ARRIVED', 'Arrived'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('EMERGENCY', 'Emergency')], default='SCHEDULED', max_length=20),
        ),
        migrations.CreateModel(
            name='FlightWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('GATE_ASSIGNED', 'Gate Assigned'), ('CREW_ASSIGNED', 'Ground Crew Assigned'), ('FUELING', 'Fuel Assigned'), ('CLEANING', 'Cleaning Started'), ('MAINTENANCE_CHECK', 'Maintenance Check'), ('BAGGAGE_LOADING', 'Baggage Loading'), ('BOARDING', 'Boarding'), ('GATE_CLOSED', 'Gate Closed'), ('PUSHBACK', 'Pushback'), ('TAXIING', 'Taxiing'), ('DEPARTED', 'Departed/Takeoff')], max_length=30)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='flights.flight')),
            ],
            options={
                'ordering': ['completed_at'],
                'unique_together': {('flight', 'step')},
            },
        ),
    ]
