# Generated by Django 5.2.15 on 2026-06-30 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_status_flightworkflowstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('fueling', 'Fueling'), ('cleaning', 'Cleaning'), ('catering', 'Catering'), ('baggage', 'Baggage Handling'), ('deicing', 'De-icing')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='flights.flight')),
            ],
            options={
                'unique_together': {('flight', 'service_type')},
            },
        ),
    ]
