# Generated by Django 5.2.15 on 2026-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flightservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='passenger_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
