# Generated by Django 5.2.15 on 2026-07-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_flight_passenger_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='length',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Fuselage length in meters, used for gate compatibility checks', max_digits=6),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='width',
            field=models.DecimalField(decimal_places=2, default=36.0, help_text='Wingspan in meters, used for gate compatibility checks', max_digits=6),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', max_length=20),
        ),
    ]
