# Generated by Django 5.2.15 on 2026-07-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_aircraft_length_aircraft_width_flight_flight_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airline',
            options={'ordering': ['name']},
        ),
    ]
