# Generated by Django 5.2.15 on 2026-07-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_alter_airline_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightworkflowstep',
            name='step',
            field=models.CharField(choices=[('GATE_ASSIGNED', 'Gate Assigned'), ('CREW_ASSIGNED', 'Ground Crew Assigned'), ('FUELING', 'Fuel Assigned'), ('CLEANING', 'Cleaning Started'), ('MAINTENANCE_CHECK', 'Maintenance Check'), ('BAGGAGE_LOADING', 'Baggage Loading'), ('BOARDING', 'Boarding'), ('GATE_CLOSED', 'Gate Closed'), ('PUSHBACK', 'Pushback'), ('TAXIING', 'Taxiing'), ('DEPARTED', 'Departed/Takeoff'), ('AIRBORNE', 'Airborne'), ('LANDING', 'Landing'), ('TAXI_TO_GATE', 'Taxi to Gate'), ('ARRIVED', 'Arrived/Landed')], max_length=30),
        ),
    ]
