# Generated by Django 5.2.15 on 2026-06-30 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0005_flightservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fuel_truck', 'Fuel Truck'), ('pushback_tractor', 'Pushback Tractor'), ('gpu', 'GPU (Ground Power Unit)'), ('baggage_trolley', 'Baggage Trolley'), ('tow_vehicle', 'Tow Vehicle'), ('conveyor_belt', 'Conveyor Belt'), ('catering_truck', 'Catering Truck'), ('deicing_truck', 'De-icing Truck')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroundEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('damaged', 'Damaged')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ground_equipment.equipmenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('equipment_type', 'equipment_id')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ground_equipment.groundequipment')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('equipment', 'flight')},
            },
        ),
    ]
